### ISSUE TITLE
The referenced license, MIT is not applicable and would cause illegal use of this package

### ISSUE THREAD

**Issue by JorjMcKie** [yigitkonur/swift-ocr-llm-powered-pdf-to-markdown#5]
PyMuPDF is available under the open-source freeware license GNU AGPL v3.0 (in addition to commercial license agreements).

Every software making use of PyMuPDF (or MuPDF) must be offered to the public under that same license.

Please update the license of this package as soon as possible.
For details, please consult [this](https://artifex.com/licensing/agpl/) website.

**Comment by ryan-mcdonough** [comment]
Yeah this is definitley an issue.

To avoid the AGPL licensing issue with PyMuPDF, I’d recommend switching to a combination of pdf2image (for converting PDFs to images) and Tesseract (for OCR). Both of these are under Apache License 2.0, which is more permissive and won’t force you to change your project’s license to AGPL.

**Comment by yigitkonur** [comment]
I appreciate the value your work has added to the project, streamlining my workflow. I promptly updated the license when the issue was raised. As noted, those with concerns can choose alternative libraries. I have no specific licensing agenda; our only considerations are the requirements of our dependencies.
